### ISSUE TITLE
Erreur trouvé dans le log cron_execution

### ISSUE THREAD

**Issue by superbricolo** [mika-nt28/Jeedom-arrosageAuto#32]
Bonjour,

Voici donc l'erreur que j'ai constaté:
`PHP Warning:  Division by zero in /var/www/html/plugins/arrosageAuto/core/class/arrosageAuto.class.php on line 163
[Erreur] arrosageAuto::pull() : DateInterval::__construct(): Unknown or bad format (PTINFS)
`

Et voici mon paramétrage
![arrosageauto1](https://user-images.githubusercontent.com/23324068/36061239-f02962ac-0e57-11e8-8643-44553fab6bce.PNG)
![arrosageauto2](https://user-images.githubusercontent.com/23324068/36061241-f3e20ed0-0e57-11e8-8131-f3a5928b147b.PNG)

Sinon, j'ai une mise en route de l'arrosage mais pas d'arrêt. Je suis en essai avec une simulation par envoi de mail.

Cordialement

superbricolo

**Comment by mika-nt28** [comment]
J'ai gerer cette erreur par contre je ne comprend pas pourquoi tu as zero.
Si je refais les calcule je te trouve un pluviométrie a 2.5, ce qui me parait logique
Qu'a tu dans les log?

**Comment by superbricolo** [comment]
Malheureusement je n'ai pas d'autres log. Je suis toujours ennuyé avec mes plantages de Jeedom.
je te redis si le problème se reproduit une autre fois, ce qui devrait arriver puisque je n'ai pas touché les paramétrages.

Cordialement

superbricolo




----- Mail original -----
De: "Halbout Michael" <notifications@github.com>
À: "mika-nt28/Jeedom-arrosageAuto" <Jeedom-arrosageAuto@noreply.github.com>
Cc: "superbricolo" <lemai.laurent@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 12 Février 2018 08:43:03
Objet: Re: [mika-nt28/Jeedom-arrosageAuto] Erreur trouvé dans le log cron_execution (#32)



J'ai gerer cette erreur par contre je ne comprend pas pourquoi tu as zero. 
Si je refais les calcule je te trouve un pluviométrie a 2.5, ce qui me parait logique 
Qu'a tu dans les log?

**Comment by superbricolo** [comment]
Bonjour,

Le cas s'est reproduit hier et curieusement je n'ai aucun log arrosageauto alors que je suis bien en mode debug. Donc je verrais si cela s'arrange avec ton correctif

superbricolo



----- Mail original -----
De: "Halbout Michael" <notifications@github.com>
À: "mika-nt28/Jeedom-arrosageAuto" <Jeedom-arrosageAuto@noreply.github.com>
Cc: "superbricolo" <lemai.laurent@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 12 Février 2018 08:43:03
Objet: Re: [mika-nt28/Jeedom-arrosageAuto] Erreur trouvé dans le log cron_execution (#32)



J'ai gerer cette erreur par contre je ne comprend pas pourquoi tu as zero. 
Si je refais les calcule je te trouve un pluviométrie a 2.5, ce qui me parait logique 
Qu'a tu dans les log?

**Comment by mika-nt28** [comment]
J'ai corrigé une erreur ce matin.
Le plugin plantait a certain moment
