### ISSUE TITLE
Acces à la page configuation impossible

### ISSUE THREAD

**Issue by vancampa** [mika-nt28/Jeedom-arrosageAuto#94]
L’accès à la page configuration n'est pas possible car la roue tourne sans  cesse.

![image](https://user-images.githubusercontent.com/19505671/53692571-98d31280-3d92-11e9-9a09-fc3bd5bc654e.png)

Peut être la cause:  Une erreur Jquery est noté dans la console "TypeError: cannot use 'in' operator to search for 'length' in '{type:[Pelouse,P...'" 

merci pour ce projet :D

**Comment by mika-nt28** [comment]
Desolé pour le retard je n'avais pas vue l'issue
Je viens de le corrigé
